export {default as HomeScreen} from '@screens/HomeScreen';
export {default as ProfileScreen} from '@screens/ProfileScreen';
export {default as DiscoverScreen} from '~/screens/DiscoverScreen';
export {default as SignInScreen} from '@screens/SignInScreen';
export {default as SignUpScreen} from '@screens/SignUpScreen';
export {default as ViewScreen} from '@screens/ViewScreen';
export {default as SearchScreen} from '@screens/SearchScreen';
export {default as WebViewScreen} from '@screens/WebViewScreen';
export {default as BookmarkScreen} from '@screens/BookmarkScreen';
